"""SQLAlchemy persistence for the bounded T149 pre-engagement surface."""

from __future__ import annotations

from collections.abc import Sequence
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.application.interfaces.enquiry_repository import EnquiryRepository
from app.infrastructure.persistence.models.enquiry import Enquiry, Quotation, QuotationRevision


class SqlAlchemyEnquiryRepository(EnquiryRepository):
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get(self, organization_id: UUID, enquiry_id: UUID) -> Enquiry | None:
        return (
            await self._session.execute(
                select(Enquiry).where(
                    Enquiry.id == enquiry_id, Enquiry.organization_id == organization_id
                )
            )
        ).scalar_one_or_none()

    async def list(self, organization_id: UUID, *, limit: int, offset: int) -> Sequence[Enquiry]:
        return (
            (
                await self._session.execute(
                    select(Enquiry)
                    .where(Enquiry.organization_id == organization_id)
                    .order_by(Enquiry.created_at, Enquiry.id)
                    .limit(limit)
                    .offset(offset)
                )
            )
            .scalars()
            .all()
        )

    async def count(self, organization_id: UUID) -> int:
        return (
            await self._session.execute(
                select(func.count())
                .select_from(Enquiry)
                .where(Enquiry.organization_id == organization_id)
            )
        ).scalar_one()

    async def add(self, enquiry: Enquiry) -> Enquiry:
        self._session.add(enquiry)
        await self._session.flush()
        return enquiry

    async def update(self, enquiry: Enquiry) -> Enquiry:
        await self._session.flush()
        # ``updated_at`` is generated by PostgreSQL's on-update expression.
        # Refresh it while we are still in the async repository boundary so
        # response serialization never attempts an implicit async lazy load.
        await self._session.refresh(enquiry)
        return enquiry

    async def get_quotation(
        self, organization_id: UUID, enquiry_id: UUID, quotation_id: UUID
    ) -> Quotation | None:
        return (
            await self._session.execute(
                select(Quotation).where(
                    Quotation.id == quotation_id,
                    Quotation.organization_id == organization_id,
                    Quotation.enquiry_id == enquiry_id,
                )
            )
        ).scalar_one_or_none()

    async def list_quotations(
        self, organization_id: UUID, enquiry_id: UUID, *, limit: int, offset: int
    ) -> Sequence[Quotation]:
        return (
            (
                await self._session.execute(
                    select(Quotation)
                    .where(
                        Quotation.organization_id == organization_id,
                        Quotation.enquiry_id == enquiry_id,
                    )
                    .order_by(Quotation.created_at, Quotation.id)
                    .limit(limit)
                    .offset(offset)
                )
            )
            .scalars()
            .all()
        )

    async def count_quotations(self, organization_id: UUID, enquiry_id: UUID) -> int:
        return (
            await self._session.execute(
                select(func.count())
                .select_from(Quotation)
                .where(
                    Quotation.organization_id == organization_id, Quotation.enquiry_id == enquiry_id
                )
            )
        ).scalar_one()

    async def add_quotation(self, quotation: Quotation) -> Quotation:
        self._session.add(quotation)
        await self._session.flush()
        return quotation

    async def lock_quotation(
        self, organization_id: UUID, enquiry_id: UUID, quotation_id: UUID
    ) -> Quotation | None:
        return (
            await self._session.execute(
                select(Quotation)
                .where(
                    Quotation.id == quotation_id,
                    Quotation.organization_id == organization_id,
                    Quotation.enquiry_id == enquiry_id,
                )
                .with_for_update()
            )
        ).scalar_one_or_none()

    async def next_revision_ordinal(self, quotation_id: UUID) -> int:
        value = (
            await self._session.execute(
                select(func.coalesce(func.max(QuotationRevision.ordinal), 0)).where(
                    QuotationRevision.quotation_id == quotation_id
                )
            )
        ).scalar_one()
        return value + 1

    async def add_revision(self, revision: QuotationRevision) -> QuotationRevision:
        self._session.add(revision)
        await self._session.flush()
        return revision

    async def get_revision(
        self, organization_id: UUID, quotation_id: UUID, revision_id: UUID
    ) -> QuotationRevision | None:
        return (
            await self._session.execute(
                select(QuotationRevision).where(
                    QuotationRevision.id == revision_id,
                    QuotationRevision.organization_id == organization_id,
                    QuotationRevision.quotation_id == quotation_id,
                )
            )
        ).scalar_one_or_none()

    async def list_revisions(
        self, organization_id: UUID, quotation_id: UUID
    ) -> Sequence[QuotationRevision]:
        return (
            (
                await self._session.execute(
                    select(QuotationRevision)
                    .where(
                        QuotationRevision.organization_id == organization_id,
                        QuotationRevision.quotation_id == quotation_id,
                    )
                    .order_by(QuotationRevision.ordinal)
                )
            )
            .scalars()
            .all()
        )

    async def update_revision(self, revision: QuotationRevision) -> QuotationRevision:
        await self._session.flush()
        return revision
