"""geography: countries, states, districts, talukas, villages

Revision ID: 198cbb4bbeb6
Revises: 4c661976b322
Create Date: 2026-08-05 12:11:24.232416

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "198cbb4bbeb6"
down_revision: str | Sequence[str] | None = "4c661976b322"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("iso_code", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("iso_code", name=op.f("uq_countries_iso_code")),
        sa.UniqueConstraint("name", name=op.f("uq_countries_name")),
    )
    op.create_table(
        "states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.id"], name=op.f("fk_states_country_id_countries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_states")),
        sa.UniqueConstraint("country_id", "name", name=op.f("uq_states_country_id")),
    )
    op.create_index(op.f("ix_states_country_id"), "states", ["country_id"], unique=False)
    op.create_table(
        "districts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["state_id"], ["states.id"], name=op.f("fk_districts_state_id_states")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
        sa.UniqueConstraint("state_id", "name", name=op.f("uq_districts_state_id")),
    )
    op.create_index(op.f("ix_districts_state_id"), "districts", ["state_id"], unique=False)
    op.create_table(
        "talukas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("district_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"], ["districts.id"], name=op.f("fk_talukas_district_id_districts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talukas")),
        sa.UniqueConstraint("district_id", "name", name=op.f("uq_talukas_district_id")),
    )
    op.create_index(op.f("ix_talukas_district_id"), "talukas", ["district_id"], unique=False)
    op.create_table(
        "villages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("taluka_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["taluka_id"], ["talukas.id"], name=op.f("fk_villages_taluka_id_talukas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_villages")),
        sa.UniqueConstraint("taluka_id", "name", name=op.f("uq_villages_taluka_id")),
    )
    op.create_index(op.f("ix_villages_taluka_id"), "villages", ["taluka_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_villages_taluka_id"), table_name="villages")
    op.drop_table("villages")
    op.drop_index(op.f("ix_talukas_district_id"), table_name="talukas")
    op.drop_table("talukas")
    op.drop_index(op.f("ix_districts_state_id"), table_name="districts")
    op.drop_table("districts")
    op.drop_index(op.f("ix_states_country_id"), table_name="states")
    op.drop_table("states")
    op.drop_table("countries")
    # ### end Alembic commands ###
