"""properties: properties, property_owners

Revision ID: 7789f56da7f9
Revises: ac077004afeb
Create Date: 2026-08-05 12:20:41.250499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7789f56da7f9"
down_revision: str | Sequence[str] | None = "ac077004afeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("property_type", sa.String(length=20), nullable=False),
        sa.Column("survey_number", sa.String(length=50), nullable=False),
        sa.Column("sub_division_number", sa.String(length=50), nullable=True),
        sa.Column("area_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("area_unit", sa.String(length=20), nullable=True),
        sa.Column("address_id", sa.Uuid(), nullable=True),
        sa.Column("village_id", sa.Uuid(), nullable=True),
        sa.Column("registration_number", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "property_type IN ('agricultural', 'residential', 'commercial', 'industrial', 'other')",
            name=op.f("ck_properties_property_type"),
        ),
        sa.CheckConstraint(
            "area_value IS NULL OR area_value > 0", name=op.f("ck_properties_area_value_positive")
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_properties_address_id_addresses")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_properties_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_properties_updated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["village_id"], ["villages.id"], name=op.f("fk_properties_village_id_villages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
    )
    op.create_index(
        op.f("ix_properties_registration_number"),
        "properties",
        ["registration_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_properties_survey_number"), "properties", ["survey_number"], unique=False
    )
    op.create_index(op.f("ix_properties_village_id"), "properties", ["village_id"], unique=False)
    op.create_table(
        "property_owners",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("ownership_share", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ownership_type", sa.String(length=50), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "ownership_share IS NULL OR (ownership_share > 0 AND ownership_share <= 100)",
            name=op.f("ck_property_owners_ownership_share_range"),
        ),
        sa.CheckConstraint(
            "to_date IS NULL OR to_date >= from_date",
            name=op.f("ck_property_owners_to_date_after_from_date"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_property_owners_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_property_owners_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_property_owners_property_id_properties"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_property_owners_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_owners")),
    )
    op.create_index(
        op.f("ix_property_owners_client_id"), "property_owners", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_property_owners_property_id"), "property_owners", ["property_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_property_owners_property_id"), table_name="property_owners")
    op.drop_index(op.f("ix_property_owners_client_id"), table_name="property_owners")
    op.drop_table("property_owners")
    op.drop_index(op.f("ix_properties_village_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_survey_number"), table_name="properties")
    op.drop_index(op.f("ix_properties_registration_number"), table_name="properties")
    op.drop_table("properties")
    # ### end Alembic commands ###
