"""documents and file storage

Revision ID: 9a68ef4298ae
Revises: c52ee7c83023
Create Date: 2026-08-05 12:27:49.569152

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a68ef4298ae"
down_revision: str | Sequence[str] | None = "c52ee7c83023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_types")),
        sa.UniqueConstraint("code", name=op.f("uq_document_types_code")),
    )
    op.create_table(
        "file_storage_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("storage_provider", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("retention_policy", sa.String(length=100), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_file_storage_records_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_storage_records")),
    )
    op.create_table(
        "document_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("file_storage_record_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_document_templates_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_templates_document_type_id_document_types"),
        ),
        sa.ForeignKeyConstraint(
            ["file_storage_record_id"],
            ["file_storage_records.id"],
            name=op.f("fk_document_templates_file_storage_record_id_file_storage_records"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_document_templates_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_templates")),
    )
    op.create_index(
        op.f("ix_document_templates_document_type_id"),
        "document_templates",
        ["document_type_id"],
        unique=False,
    )
    op.create_table(
        "document_variables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_template_id", sa.Uuid(), nullable=False),
        sa.Column("variable_name", sa.String(length=100), nullable=False),
        sa.Column("variable_label", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("default_value", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_template_id"],
            ["document_templates.id"],
            name=op.f("fk_document_variables_document_template_id_document_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_variables")),
        sa.UniqueConstraint(
            "document_template_id",
            "variable_name",
            name=op.f("uq_document_variables_document_template_id"),
        ),
    )
    op.create_index(
        op.f("ix_document_variables_document_template_id"),
        "document_variables",
        ["document_template_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("matter_id", sa.Uuid(), nullable=False),
        sa.Column("document_type_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_documents_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_documents_document_type_id_document_types"),
        ),
        sa.ForeignKeyConstraint(
            ["matter_id"], ["matters.id"], name=op.f("fk_documents_matter_id_matters")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_documents_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_document_type_id"), "documents", ["document_type_id"], unique=False
    )
    op.create_index(op.f("ix_documents_matter_id"), "documents", ["matter_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_storage_record_id", sa.Uuid(), nullable=False),
        sa.Column("change_summary", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_document_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["file_storage_record_id"],
            ["file_storage_records.id"],
            name=op.f("fk_document_versions_file_storage_record_id_file_storage_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version_number", name=op.f("uq_document_versions_document_id")
        ),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_matter_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        op.f("ix_document_variables_document_template_id"), table_name="document_variables"
    )
    op.drop_table("document_variables")
    op.drop_index(op.f("ix_document_templates_document_type_id"), table_name="document_templates")
    op.drop_table("document_templates")
    op.drop_table("file_storage_records")
    op.drop_table("document_types")
    # ### end Alembic commands ###
