"""clients: addresses, clients, client_contacts

Revision ID: ac077004afeb
Revises: 198cbb4bbeb6
Create Date: 2026-08-05 12:16:18.349775

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac077004afeb"
down_revision: str | Sequence[str] | None = "198cbb4bbeb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("village_id", sa.Uuid(), nullable=True),
        sa.Column("taluka_id", sa.Uuid(), nullable=True),
        sa.Column("district_id", sa.Uuid(), nullable=True),
        sa.Column("state_id", sa.Uuid(), nullable=True),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("address_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "address_type IN ('registered', 'mailing', 'property', 'other')",
            name=op.f("ck_addresses_address_type"),
        ),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.id"], name=op.f("fk_addresses_country_id_countries")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_addresses_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["district_id"], ["districts.id"], name=op.f("fk_addresses_district_id_districts")
        ),
        sa.ForeignKeyConstraint(
            ["state_id"], ["states.id"], name=op.f("fk_addresses_state_id_states")
        ),
        sa.ForeignKeyConstraint(
            ["taluka_id"], ["talukas.id"], name=op.f("fk_addresses_taluka_id_talukas")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_addresses_updated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["village_id"], ["villages.id"], name=op.f("fk_addresses_village_id_villages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(op.f("ix_addresses_village_id"), "addresses", ["village_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_type", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("primary_phone", sa.String(length=20), nullable=False),
        sa.Column("primary_email", sa.String(length=255), nullable=True),
        sa.Column("pan_number", sa.String(length=10), nullable=True),
        sa.Column("aadhaar_number", sa.String(length=12), nullable=True),
        sa.Column("address_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "aadhaar_number IS NULL OR aadhaar_number ~ '^[0-9]{12}$'",
            name=op.f("ck_clients_aadhaar_number_format"),
        ),
        sa.CheckConstraint(
            "client_type IN ('individual', 'organization')", name=op.f("ck_clients_client_type")
        ),
        sa.CheckConstraint(
            "pan_number IS NULL OR pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'",
            name=op.f("ck_clients_pan_number_format"),
        ),
        sa.CheckConstraint(
            "length(primary_phone) >= 7", name=op.f("ck_clients_primary_phone_length")
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_clients_address_id_addresses")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_clients_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_clients_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_full_name"), "clients", ["full_name"], unique=False)
    op.create_index(op.f("ix_clients_primary_email"), "clients", ["primary_email"], unique=False)
    op.create_index(op.f("ix_clients_primary_phone"), "clients", ["primary_phone"], unique=False)
    op.create_table(
        "client_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_client_contacts_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_client_contacts_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_client_contacts_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_contacts")),
    )
    op.create_index(
        op.f("ix_client_contacts_client_id"), "client_contacts", ["client_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_contacts_client_id"), table_name="client_contacts")
    op.drop_table("client_contacts")
    op.drop_index(op.f("ix_clients_primary_phone"), table_name="clients")
    op.drop_index(op.f("ix_clients_primary_email"), table_name="clients")
    op.drop_index(op.f("ix_clients_full_name"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_addresses_village_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
