"""ocr qr and backups

Revision ID: ac2214fdce03
Revises: 07150e442816
Create Date: 2026-08-05 12:40:42.047658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac2214fdce03"
down_revision: str | Sequence[str] | None = "07150e442816"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("backup_type", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_backups_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backups")),
    )
    op.create_table(
        "qr_code_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("code_value", sa.String(length=255), nullable=False),
        sa.Column("qr_image_file_storage_record_id", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_qr_code_records_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["qr_image_file_storage_record_id"],
            ["file_storage_records.id"],
            name=op.f("fk_qr_code_records_qr_image_file_storage_record_id_file_storage_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qr_code_records")),
        sa.UniqueConstraint("code_value", name=op.f("uq_qr_code_records_code_value")),
    )
    op.create_index(
        "ix_qr_code_records_entity_type_entity_id",
        "qr_code_records",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "ocr_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_ocr_jobs_document_version_id_document_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_jobs")),
    )
    op.create_index(
        op.f("ix_ocr_jobs_document_version_id"), "ocr_jobs", ["document_version_id"], unique=False
    )
    op.create_table(
        "ocr_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ocr_job_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ocr_job_id"], ["ocr_jobs.id"], name=op.f("fk_ocr_results_ocr_job_id_ocr_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_results")),
    )
    op.create_index(
        "ix_ocr_results_extracted_text_fts",
        "ocr_results",
        [sa.literal_column("to_tsvector('english', extracted_text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_ocr_results_ocr_job_id"), "ocr_results", ["ocr_job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ocr_results_ocr_job_id"), table_name="ocr_results")
    op.drop_index(
        "ix_ocr_results_extracted_text_fts", table_name="ocr_results", postgresql_using="gin"
    )
    op.drop_table("ocr_results")
    op.drop_index(op.f("ix_ocr_jobs_document_version_id"), table_name="ocr_jobs")
    op.drop_table("ocr_jobs")
    op.drop_index("ix_qr_code_records_entity_type_entity_id", table_name="qr_code_records")
    op.drop_table("qr_code_records")
    op.drop_table("backups")
    # ### end Alembic commands ###
