"""matters and workflow

Revision ID: c52ee7c83023
Revises: 7789f56da7f9
Create Date: 2026-08-05 12:23:49.020159

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c52ee7c83023"
down_revision: str | Sequence[str] | None = "7789f56da7f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matter_statuses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matter_statuses")),
        sa.UniqueConstraint("code", name=op.f("uq_matter_statuses_code")),
    )
    op.create_table(
        "matter_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matter_types")),
        sa.UniqueConstraint("code", name=op.f("uq_matter_types_code")),
    )
    op.create_table(
        "workflow_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_workflow_definitions_code")),
    )
    op.create_table(
        "workflow_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_definition_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_initial", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_workflow_states_workflow_definition_id_workflow_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_states")),
        sa.UniqueConstraint(
            "workflow_definition_id", "code", name=op.f("uq_workflow_states_workflow_definition_id")
        ),
    )
    op.create_index(
        op.f("ix_workflow_states_workflow_definition_id"),
        "workflow_states",
        ["workflow_definition_id"],
        unique=False,
    )
    op.create_table(
        "workflow_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_definition_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("from_state_id", sa.Uuid(), nullable=True),
        sa.Column("to_state_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("transitioned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "transitioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_state_id"],
            ["workflow_states.id"],
            name=op.f("fk_workflow_history_from_state_id_workflow_states"),
        ),
        sa.ForeignKeyConstraint(
            ["to_state_id"],
            ["workflow_states.id"],
            name=op.f("fk_workflow_history_to_state_id_workflow_states"),
        ),
        sa.ForeignKeyConstraint(
            ["transitioned_by"],
            ["users.id"],
            name=op.f("fk_workflow_history_transitioned_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_workflow_history_workflow_definition_id_workflow_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_history")),
    )
    op.create_index(
        "ix_workflow_history_entity_type_entity_id",
        "workflow_history",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_history_workflow_definition_id"),
        "workflow_history",
        ["workflow_definition_id"],
        unique=False,
    )
    op.create_table(
        "matters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("matter_number", sa.String(length=50), nullable=False),
        sa.Column("matter_type_id", sa.Uuid(), nullable=False),
        sa.Column("matter_status_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "closed_at IS NULL OR closed_at >= opened_at",
            name=op.f("ck_matters_closed_at_after_opened_at"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_matters_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_matters_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_matters_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["matter_status_id"],
            ["matter_statuses.id"],
            name=op.f("fk_matters_matter_status_id_matter_statuses"),
        ),
        sa.ForeignKeyConstraint(
            ["matter_type_id"],
            ["matter_types.id"],
            name=op.f("fk_matters_matter_type_id_matter_types"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"], ["properties.id"], name=op.f("fk_matters_property_id_properties")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_matters_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matters")),
        sa.UniqueConstraint("matter_number", name=op.f("uq_matters_matter_number")),
    )
    op.create_index(op.f("ix_matters_assigned_to"), "matters", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_matters_client_id"), "matters", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_matters_matter_status_id"), "matters", ["matter_status_id"], unique=False
    )
    op.create_index(op.f("ix_matters_matter_type_id"), "matters", ["matter_type_id"], unique=False)
    op.create_index(op.f("ix_matters_property_id"), "matters", ["property_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matters_property_id"), table_name="matters")
    op.drop_index(op.f("ix_matters_matter_type_id"), table_name="matters")
    op.drop_index(op.f("ix_matters_matter_status_id"), table_name="matters")
    op.drop_index(op.f("ix_matters_client_id"), table_name="matters")
    op.drop_index(op.f("ix_matters_assigned_to"), table_name="matters")
    op.drop_table("matters")
    op.drop_index(op.f("ix_workflow_history_workflow_definition_id"), table_name="workflow_history")
    op.drop_index("ix_workflow_history_entity_type_entity_id", table_name="workflow_history")
    op.drop_table("workflow_history")
    op.drop_index(op.f("ix_workflow_states_workflow_definition_id"), table_name="workflow_states")
    op.drop_table("workflow_states")
    op.drop_table("workflow_definitions")
    op.drop_table("matter_types")
    op.drop_table("matter_statuses")
    # ### end Alembic commands ###
